apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: kube-vault
  annotations:
    dns.alpha.kubernetes.io/external: "vault.gde.gigsternetwork.com"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:569325332953:certificate/a130e06a-54ff-490e-945d-5fccd33766f6
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
  labels:
    name: vault
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8200
    - name: server
      port: 8201
      protocol: "TCP"
      targetPort: 8201
  selector:
    app: vault
