apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault
  labels:
    name: vault
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8200
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8200
    - name: server
      port: 8201
      protocol: "TCP"
      targetPort: 8201
  selector:
    app: vault
